CONVERT_TO				= promicro_rp2040
TAP_DANCE_ENABLE 		= yes
PERMISSIVE_HOLD 		= yes
MOUSEKEY_ENABLE 		= no     # Mouse keys
VIA_ENABLE      		= yes    # Enable VIA
LTO_ENABLE      		= no	 # smaller output
COMBO_ENABLE 			= yes
CAPS_WORD_ENABLE 		= yes
DEFERRED_EXEC_ENABLE 	= yes
